MATERIAL_DICT = {'king': 0, 'pawn': 1, 'knight': 3, 'bishop': 3, 'rook': 5, 'queen': 9}
ALL_SQUARES = []
for f in 'abcdefgh':
    for r in '12345678':
        ALL_SQUARES.append(f + r)

# CHECKMATE SCORE
CHECKMATE_SCORE = 999999

# SCORES FOR SQUARES CONTROLLED BY PAWNS
CENTRAL_FILE_4TH_RANK = 0.15
CENTRAL_FILE_5TH_RANK = 0.18
CENTRAL_FILE_6TH_RANK = 0.20
BISHOP_FILE_4TH_RANK = 0.13
BISHOP_FILE_5TH_RANK = 0.15
BISHOP_FILE_6TH_RANK = 0.18
SEVENTH_RANK = 0.20
KNIGHT_FILE_5TH_RANK = 0.13
KNIGHT_FILE_6TH_RANK = 0.15
ALL_OTHERS = 0.1

SEVENTH_RANK_SCORES = {}
for f in 'abcdefgh':
    SEVENTH_RANK_SCORES[f] = SEVENTH_RANK
SIXTH_RANK_SCORES = {'a': ALL_OTHERS, 'b': KNIGHT_FILE_6TH_RANK, 'c': BISHOP_FILE_6TH_RANK, 'd': CENTRAL_FILE_6TH_RANK,
                     'e': CENTRAL_FILE_6TH_RANK, 'f': BISHOP_FILE_6TH_RANK, 'g': KNIGHT_FILE_6TH_RANK, 'h': ALL_OTHERS}
FIFTH_RANK_SCORES = {'a': ALL_OTHERS, 'b': KNIGHT_FILE_5TH_RANK, 'c': BISHOP_FILE_5TH_RANK, 'd': CENTRAL_FILE_5TH_RANK,
                     'e': CENTRAL_FILE_5TH_RANK, 'f': BISHOP_FILE_5TH_RANK, 'g': KNIGHT_FILE_5TH_RANK, 'h': ALL_OTHERS}
FOURTH_RANK_SCORES = {'a': ALL_OTHERS, 'b': ALL_OTHERS, 'c': BISHOP_FILE_4TH_RANK, 'd': CENTRAL_FILE_4TH_RANK,
                      'e': CENTRAL_FILE_4TH_RANK, 'f': BISHOP_FILE_4TH_RANK, 'g': ALL_OTHERS, 'h': ALL_OTHERS}
RANK_SCORES = {'4': FOURTH_RANK_SCORES, '5': FIFTH_RANK_SCORES, '6': SIXTH_RANK_SCORES, '7': SEVENTH_RANK_SCORES}
WHITE_PAWN_CONTROL_SCORES = {}
BLACK_PAWN_CONTROL_SCORES = {}
for square in ALL_SQUARES:
    file = square[0]
    rank = square[1]
    if rank in RANK_SCORES:
        WHITE_PAWN_CONTROL_SCORES[square] = RANK_SCORES[rank][file]
    else:
        WHITE_PAWN_CONTROL_SCORES[square] = ALL_OTHERS

for square in WHITE_PAWN_CONTROL_SCORES:
    rank = int(square[1])
    black_rank = 9 - rank
    mirrored_square = square[0] + str(black_rank)
    BLACK_PAWN_CONTROL_SCORES[mirrored_square] = WHITE_PAWN_CONTROL_SCORES[square]

# MULTIPLIER FOR NUMBER OF LEGAL PIECE MOVES AVAILABLE
LEGAL_PIECE_MOVE_MULTIPLIER = 0.1